CREATE TABLE auth_token (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  token VARCHAR(255) NOT NULL UNIQUE,
  type ENUM('PASSWORD_RESET', 'EMAIL_VERIFICATION', 'ACCOUNT_ACTIVATION', 'REFRESH') NOT NULL,
  expiry_date DATETIME NOT NULL,
  used TINYINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);
