-- MySQL Script generated by MySQL Workbench
-- Mon Oct  6 10:34:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema internship_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema internship_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `internship_management` DEFAULT CHARACTER SET utf8 ;
USE `internship_management` ;

-- -----------------------------------------------------
-- Table `internship_management`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internship_management`.`roles` ;

CREATE TABLE IF NOT EXISTS `internship_management`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internship_management`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internship_management`.`company` ;

CREATE TABLE IF NOT EXISTS `internship_management`.`company` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(75) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internship_management`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internship_management`.`department` ;

CREATE TABLE IF NOT EXISTS `internship_management`.`department` (
  `department_id` INT NOT NULL AUTO_INCREMENT,
  `department_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internship_management`.`field_of_study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internship_management`.`field_of_study` ;

CREATE TABLE IF NOT EXISTS `internship_management`.`field_of_study` (
  `field_of_study_id` INT NOT NULL AUTO_INCREMENT,
  `field_of_study_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`field_of_study_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internship_management`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internship_management`.`users` ;

CREATE TABLE IF NOT EXISTS `internship_management`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(320) NOT NULL,
  `email_alternate` VARCHAR(320) NULL,
  `phone_number` VARCHAR(13) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `active` TINYINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `company_id` INT NULL,
  `admin_referal` VARCHAR(6) NULL,
  `password_needs_change` TINYINT NOT NULL,
  `department_id` INT NULL,
  `study_field_of_study_id` INT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_users_roles1_idx` (`roles_role_id` ASC),
  INDEX `fk_users_company1_idx` (`company_id` ASC),
  INDEX `fk_users_department1_idx` (`department_id` ASC),
  INDEX `fk_users_field_of_study1_idx` (`study_field_of_study_id` ASC),
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`roles_role_id`)
    REFERENCES `internship_management`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `internship_management`.`company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `internship_management`.`department` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_field_of_study1`
    FOREIGN KEY (`field_of_study_id`)
    REFERENCES `internship_management`.`field_of_study` (`field_of_study_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internship_management`.`internship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internship_management`.`internship` ;

CREATE TABLE IF NOT EXISTS `internship_management`.`internship` (
  `internship_id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  `academic_year` VARCHAR(9) NOT NULL,
  `semester` INT NOT NULL,
  `date_start` DATE NOT NULL,
  `date_end` DATE NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`internship_id`),
  INDEX `fk_internship_company1_idx` (`company_id` ASC),
  INDEX `fk_internship_users1_idx` (`student_id` ASC),
  CONSTRAINT `fk_internship_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `internship_management`.`company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_internship_users1`
    FOREIGN KEY (`student_id`)
    REFERENCES `internship_management`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internship_management`.`document_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internship_management`.`document_type` ;

CREATE TABLE IF NOT EXISTS `internship_management`.`document_type` (
  `document_type_id` INT NOT NULL AUTO_INCREMENT,
  `document_type_name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`document_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internship_management`.`documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internship_management`.`documents` ;

CREATE TABLE IF NOT EXISTS `internship_management`.`documents` (
  `document_id` INT NOT NULL AUTO_INCREMENT,
  `document_type_id` INT NOT NULL,
  `internship_id` INT NOT NULL,
  `document_name` VARCHAR(255) NOT NULL,
  `uploaded_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`document_id`),
  INDEX `fk_documents_document_type_idx` (`document_type_id` ASC),
  INDEX `fk_documents_internship1_idx` (`internship_id` ASC),
  CONSTRAINT `fk_documents_document_type`
    FOREIGN KEY (`document_type_id`)
    REFERENCES `internship_management`.`document_type` (`document_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documents_internship1`
    FOREIGN KEY (`internship_id`)
    REFERENCES `internship_management`.`internship` (`internship_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internship_management`.`internship_state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internship_management`.`internship_state` ;

CREATE TABLE IF NOT EXISTS `internship_management`.`internship_state` (
  `internship_state_id` INT NOT NULL AUTO_INCREMENT,
  `internship_state_name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`internship_state_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internship_management`.`internship_state_change`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internship_management`.`internship_state_change` ;

CREATE TABLE IF NOT EXISTS `internship_management`.`internship_state_change` (
  `internship_state_change_id` INT NOT NULL AUTO_INCREMENT,
  `internship_id` INT NOT NULL,
  `internship_state_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `state_changed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`internship_state_change_id`),
  INDEX `fk_internship_state_change_internship_state1_idx` (`internship_state_id` ASC),
  INDEX `fk_internship_state_change_internship1_idx` (`internship_id` ASC),
  INDEX `fk_internship_state_change_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_internship_state_change_internship_state1`
    FOREIGN KEY (`internship_state_id`)
    REFERENCES `internship_management`.`internship_state` (`internship_state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_internship_state_change_internship1`
    FOREIGN KEY (`internship_id`)
    REFERENCES `internship_management`.`internship` (`internship_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_internship_state_change_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `internship_management`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internship_management`.`timestatement_state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internship_management`.`timestatement_state` ;

CREATE TABLE IF NOT EXISTS `internship_management`.`timestatement_state` (
  `timestatement_state_id` INT NOT NULL AUTO_INCREMENT,
  `timestatement_state_name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`timestatement_state_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internship_management`.`timestatement_state_change`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internship_management`.`timestatement_state_change` ;

CREATE TABLE IF NOT EXISTS `internship_management`.`timestatement_state_change` (
  `timestatement_state_change_id` INT NOT NULL AUTO_INCREMENT,
  `document_id` INT NOT NULL,
  `timestatement_state_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `state_changed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`timestatement_state_change_id`),
  INDEX `fk_timestatement_state_change_timestatement_state1_idx` (`timestatement_state_id` ASC),
  INDEX `fk_timestatement_state_change_users1_idx` (`employee_id` ASC),
  INDEX `fk_timestatement_state_change_documents1_idx` (`document_id` ASC),
  CONSTRAINT `fk_timestatement_state_change_timestatement_state1`
    FOREIGN KEY (`timestatement_state_id`)
    REFERENCES `internship_management`.`timestatement_state` (`timestatement_state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timestatement_state_change_users1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `internship_management`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timestatement_state_change_documents1`
    FOREIGN KEY (`document_id`)
    REFERENCES `internship_management`.`documents` (`document_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
